name: comment
on:
  pull_request:
    types: [opened]
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: circa10a/animal-action@v0.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
