name: comment
on:
  pull_request:
    types: [opened]
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: circa10a/animal-action@moar_animals
        with:
          github_token: ${{ secrets.github_token }}
